# 01 - Data Exploration
Goal: understand the MovieLens small dataset before building any models.\
Questions: how many users and movies, how ratings are distributed, how sparse data is.

## Setup

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Load the data

In [2]:
ratings_df = pd.read_csv('../data/ml-latest-small/ratings.csv')
movies_df = pd.read_csv('../data/ml-latest-small/movies.csv')

In [3]:
# Print the first few rows of rating
ratings_df.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [4]:
# Print the first few rows of movies
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [5]:
# Print shape of each dataframe (row, column)
print(ratings_df.shape)
print(movies_df.shape)

(100836, 4)
(9742, 3)

## Notes
- Ratings timestamps are Unix time (sec since 1970), will need converting to dates
- Genres are pipe-separated in one column